manifest:
  comp:
    ae:
      export:
      footage:
      lut:
      PastedImages:
      scripts:
    ai:
      export:
    b3d:
      scenes:
      assets:
    c4d:
      scenes:
        alembic:
        backup:
        c4dsrc:
        fbx:
        obj:
        orbx:
        render:
        tex:
        xpcache:
      assets:
        alembic:
        backup:
        fbx:
        obj:
        orbx:
        render:
        tex:
        xpcache:
    fusion:
      render:
    md:
    pr:
      export:
    ps:
      export:
    resolve:
      archive:
      export:
      footage:
    sbp:
    unity:
    zbrush:
  in:
    \_.*\:
    \[0-9]{4}-[0-9]{2}-[0-9]{2}_.*\:
  out:
    \_.*\:
    \[0-9]{4}-[0-9]{2}-[0-9]{2}_.*\:
  portfolio:

ignored: [" Logs", "Auto-Save", "^\\..*$", "\\(.*?\\)"]
